language: go
go_import_path: github.com/janekolszak/idp
go:
  - 1.7
  - 1.8

install:
  - sudo add-apt-repository ppa:masterminds/glide -y && sudo apt-get update
  - sudo apt-get install glide
  - glide install

script:
  - go test $(glide nv)


