language: go
go_import_path: github.com/janekolszak/idp
go:
  - 1.6

install:
  - sudo add-apt-repository ppa:masterminds/glide -y && sudo apt-get update
  - sudo apt-get install glide
  - glide install

script:
  - go build github.com/janekolszak/idp/example/idp
  - go test github.com/janekolszak/idp/helpers
  - go test github.com/janekolszak/idp/providers/basic
  - go test github.com/janekolszak/idp/providers/cookie
  - go test github.com/janekolszak/idp/providers/form
  - go test github.com/janekolszak/idp/userdb/memory
