language: go
go:
  - 1.6

install:
  - sudo add-apt-repository ppa:masterminds/glide -y && sudo apt-get update
  - sudo apt-get install glide
  - glide install

script:
  - go build ./example/idp
  - go test ./helpers
  - go test ./providers/basic
  - go test ./providers/cookie
  - go test ./providers/form
  - go test ./userdb/memory
