language: go
go:
  - 1.6

install:
  - sudo add-apt-repository ppa:masterminds/glide -y && sudo apt-get update
  - sudo apt-get install glide
  - glide install

script:
  - go test github.com/janekolszak/idp/helpers
  - go test github.com/janekolszak/idp/providers
