version: '2'

services:

  db:
    image: rethinkdb:latest
    container_name: db
    restart: always
    volumes:
        - dbvolume:/var/lib/rethinkdb
    cpu_quota: 50000

  hydra:
    container_name: hydra
    build:
      context: ./hydra
    volumes:
      - hydravolume:/root
    ports:
      - "4444:4444"
    environment:
      - SYSTEM_SECRET=passwordtutorialpasswordtutorial
      - CONSENT_URL=http://localhost:3000
      - HTTPS_TLS_KEY_PATH=/etc/hydra/key.pem
      - HTTPS_TLS_CERT_PATH=/etc/hydra/cert.pem
    cpu_quota: 50000

  idp:
    container_name: idp
    build:
      context: ../../
      dockerfile: idp-form-with-rethinkdb.dockerfile
    environment:
      - HYDRA_URL=https://hydra:4444
    links:
      - hydra
    volumes:
      - hydravolume:/root
    ports:
      - "3000:3000"
    cpu_quota: 50000

volumes:
  hydravolume:
    driver: local

  dbvolume:
    driver: local